FROM almalinux:9
#CMD [ "ping","-c5","google.com" ]
#ENTRYPOINT [ "ping","-c5","google.com" ]
CMD [ "google.com" ]
ENTRYPOINT [ "ping","-c5" ]
#ENTRYPOINT and CMD command can be combined for better usage CMD will overwrite
#docker run cmd:1.0 ping -c5 yahoo.com <this is for commented>
#docker run cmd:1.0 yahoo.com