ARG version
FROM almalinux:${version}
ARG course
ARG Triner
RUN echo "Course is ${course}, Triner is ${Triner}"
#RUN cat /etc/*release
CMD [ "sleep","120" ]
#docker build -t arg:v1.0.0 --build-arg version=8 .