FROM almalinux:9
ADD https://github.com/gubbalarajesh91/Session/blob/main/SessionNotes/session-06.txt /tmp
ADD sample-1.tar /tmp/ 
#this will untar the files and place it in /tmp/
CMD [ "sleep","120" ]